# Numpy进阶 Homework

2021.4.13

**本次作业将完成numpy迭代器和ufunc的基本操作** 

### 1.单维迭代器
分别以C,F以及默认顺序遍历a矩阵，观察输出结果（*提示：`np.nditer()`函数包含参数 `order`*）

In [1]:
import numpy as np
a = np.arange(6).reshape(2, 3)
print(a)
for x in np.nditer(a):
    print(x, end=',')
print()
for x in np.nditer(a, order = 'C'):
    print(x, end=',')
print()
for x in np.nditer(a, order = 'F'):
    print(x, end=',')


[[0 1 2]
 [3 4 5]]
0,1,2,3,4,5,
0,1,2,3,4,5,
0,3,1,4,2,5,

**用两种方法实现：**利用迭代器遍历矩阵a，要求返回值顺序为`0,3,1,4,2,5`

In [2]:
for x in np.nditer(a.T, order='C'):
    print (x, end=", " )
print()
for x in np.nditer(a, order='F'):
    print (x, end=", " )
print()

0, 3, 1, 4, 2, 5, 
0, 3, 1, 4, 2, 5, 


### 2.外部循环
在使用外部循环`external_loop`模式的基础上，**用两种方法实现：**将a矩阵各元素扩大为原来2倍*（提示：C，F及默认顺序任选其二）*

In [3]:
a = np.arange(8).reshape(2, 4)

for x in np.nditer(a, flags=['external_loop'], op_flags=['readwrite']):
    x[...]=x*2
print(a)
for x in np.nditer(a, flags=['external_loop'], op_flags=['readwrite'], order = 'F'):
    x[...]=x*2
print(a)

[[ 0  2  4  6]
 [ 8 10 12 14]]
[[ 0  4  8 12]
 [16 20 24 28]]


定义矩阵$A^{m*1}, B^{1*n}$，令$C^{m*n} = AB$，则C为秩一矩阵，要求利用numpy迭代器的`multi_index`模式，实现求C的过程

In [4]:
A = np.arange(5).reshape(5,1) + 1
B = np.arange(3).reshape(1,3) + 1

print(A)
print(B)
C = np.empty([5,3], dtype=int)
idx = np.nditer([A,B], flags =  ['multi_index'])

while not idx.finished:
    C[idx.multi_index]=idx[0]*idx[1]
    is_not_finished = idx.iternext()

print(C)

[[1]
 [2]
 [3]
 [4]
 [5]]
[[1 2 3]]
[[ 1  2  3]
 [ 2  4  6]
 [ 3  6  9]
 [ 4  8 12]
 [ 5 10 15]]


### 3.U_function
自定义一个numpy的ufunc函数，实现`z = 2*x*x+12*y*y`的计算任务，并与利用`numpy`函数实现该任务比较计算时长

In [5]:
import time
x = list(range(10000))
y = list(range(10000))
def f(x,y):
    return 2*x*x+12*y*y
x = np.array(x)
y = np.array(y)

g = np.frompyfunc(f,2,1)
t=time.time()
z = g(x,y)
t=time.time()-t
print(f"time used:{t}s\n{z}")

t=time.time()
z = 2*x*x+12*y*y
t=time.time()-t
print(f"time used:{t}s\n{z}")

time used:0.0019998550415039062s
[0 14 56 ... 1399160126 1399440056 1399720014]
time used:0.0010027885437011719s
[         0         14         56 ... 1399160126 1399440056 1399720014]
